### ISSUE TITLE
How I can test your project 

### ISSUE THREAD

**Issue by djmv** [dapicard/opencv-parallelize-example#1]
Could you please provide me an example, how can I test this with opencv?
I'm using opencv with cuda and c++

**Comment by dapicard** [comment]
You have to build and run it using Bazel.
At this repository root folder, do :
`bazel run:parallelize`

**Comment by djmv** [comment]
I tried to run but got errors. I followed this step. 
1. Download your repo.(previously install bazel)
2. Go to inside the folder project
3. run `bazel run:parallelize` and got this. 

`bazel run:parallelize
Starting local Bazel server and connecting to it...
Command 'run:parallelize' not found. Try 'bazel help'.`

![image](https://user-images.githubusercontent.com/19581489/53532392-c125ed00-3ac4-11e9-9cbc-12d7144a3a85.png)

4. Also I tried this. 
`bazel run` 

![image](https://user-images.githubusercontent.com/19581489/53532437-e61a6000-3ac4-11e9-92be-27f69264254d.png)

5.  Also `bazel run parallelize`
bazel run parallelize

![image](https://user-images.githubusercontent.com/19581489/53532482-09450f80-3ac5-11e9-9b30-201357348cf4.png)

I'm inside root folder of project when run above commands. 

Thanks,

**Comment by dapicard** [comment]
My mistake ; type :
`bazel run main:parallelize`

**Comment by djmv** [comment]
> My mistake ; type :
> `bazel run main:parallelize`

I got this
![image](https://user-images.githubusercontent.com/19581489/53578718-2a9a1000-3b46-11e9-9a5c-1c0a8384a18e.png)

**Comment by djmv** [comment]
> My mistake ; type :
> `bazel run main:parallelize`

I got this error: 
```
INFO: Invocation ID: 682dd709-0d94-4f4c-8dd4-e2596fa37e2e
DEBUG: Rule 'rwqueue' modified arguments {"shallow_since": "1519150107 -0500"}
INFO: Analysed target //main:parallelize (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: opencv-parallelize-example/main/BUILD:17:1: C++ compilation of rule '//main:parallelize' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 49 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
main/main.cc:25:31: fatal error: systemd/sd-daemon.h: No such file or directory
compilation terminated.
Target //main:parallelize failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.585s, Critical Path: 0.35s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by dapicard** [comment]
`
main/main.cc:25:31: fatal error: systemd/sd-daemon.h: No such file or directory
`
Install systemd headers package.

**Comment by djmv** [comment]
Thanks, I solved this installing ``` sudo apt install libsystemd-dev ``` and project run well :+1:
