### ISSUE TITLE
test the project 

### ISSUE THREAD

**Issue by Alex150M** [dapicard/opencv-parallelize-example#4]
Hello Mr @dapicard 
I try to install bazel on a jetson card with which I work and I find that bazel is not supported by the 32-bit platform, and never being working with bazel.
is it possible to have a CMakeLists.txt file for your project (to test it)?
best regards

**Comment by dapicard** [comment]
bazel is not an IDE, it's a build manager.
I don't plan to do the same with CMake, but I'm pretty sure that you can do it easilly.
